### ISSUE TITLE
Head wind or Tail wind display using GPS speed and Air speed values if possible.

### ISSUE THREAD

**Issue by ninja-zx11** [teckel12/LuaTelemetry#120]

**Comment by teckel12** [comment]
@ninja-zx11 I believe wind speed is being worked on in INAV.  Once this is sorted out, this data could be sent as telemetry information.  I don't fly fixed wing so wind speed isn't of much value.  I also don't have a pitot sensor to work on the code if it was done in the transmitter.

If you have a pitot sensor, I would appreciate telemetry logs.  Turn logging on for all telemetry sensors and set your transmitter to log telemetry.  This is a good idea to do anyway if you're not already doing it.  In any case, if you can send me some telemetry logs I could use it for a simulation and write wind speed coding in the transmitter.

**Comment by ninja-zx11** [comment]
I don't have fixed wing assembled for INAV yet but will be setting up soon with matek f405 wing F4 board , GPS and pitot tube sensor.Then i will generate the logs you mentioned.
Thanks for providing LUA telemetry on Qx7 Tx!!
