### ISSUE TITLE
Please add voice notifications for altitude similar to % battery remaining.

### ISSUE THREAD

**Issue by ninja-zx11** [teckel12/LuaTelemetry#134]
Is it possible to have voice notifications for altitude (eg every 5m or 10m) as well like battery % remaining.

**Comment by teckel12** [comment]
I assume you fly fixed wing. As I don't, I don't know what's important and what isn't.

Would vario beeping be more informative? Would voice altitude reporting be everytime the altitude changed by 5, 10 feet or whatever, or would it report the altitude every several seconds?

I like the idea, just trying to understand what would work best.

**Comment by ninja-zx11** [comment]
I fly both but i don't have OSD (i have connex prosight) on my quad and thought it will be useful for someone not having osd. and yes vario beeping would be useful for fixed wing pilots too!!
I think if we have an option of selecting voice altitude reporting everytime the altitude changes by 5,10,15 etc,then pilots can change it according to their taste.eg having an option of reporting @ 5,10,15 and 20 etc.Thanks

**Comment by teckel12** [comment]
Should be fairly easy to implement. I'll look into it tomorrow. With all that's being added in the next release, I may change the version to 1.4.0.

**Comment by teckel12** [comment]
Added help wanted label for testing of the vario beeper and voice notifications. I'm going to look for scripts that do vario beeping to see how they're implemented and compare to the one I wrote in a vacuum (as I don't fly fixed wing).

See above for installing the development branch (it's super simple moving 2 files to the transmitter).

Any feedback would be greatly appreciated!

**Comment by ninja-zx11** [comment]
That's awesome Tim!! Just copied new files to my QX7 and will be testing soon.Set my notifications to 10m.Will report back soon.

**Comment by teckel12** [comment]
@ninja-zx11 It looks like RC3 and RC4 introduce a few new problems.  One of which directly effects Lua Telemetry.  The Tmp1 sensor is mangled in RC3 and RC4.  This is the primary sensor used for flight modes.

Looking into it now...

**Comment by teckel12** [comment]
False alarm.  Works fine if you set the correct receiver protocol! 🤦‍♂️

**Comment by teckel12** [comment]
See at #136 Variometer beeping and graph are all wrong, and need rework.  

The vario voice, however, seems good!

**Comment by teckel12** [comment]
I late added the 50 m/ft setting. I'll verify it works.

**Comment by teckel12** [comment]
Fixed the issue when setting it to 50m. Just upgrade to the latest development branch like before.

**Comment by ninja-zx11** [comment]
Thanks.I will upgrade.

**Comment by Gregmaan** [comment]
@teckel12 There is still a minor issue with the voice output of the height:
- Configured voice output every 20m
- Fly at e.g. 100m ->voice 100m
- Go down to 99m -> voice 80m
..and so on.

**Comment by teckel12** [comment]
@Gregmaan Good catch!  Development branch updated which should take care of this.
