### ISSUE TITLE
x9e Rotary Encoder doesnt work

### ISSUE THREAD

**Issue by Peschi90** [teckel12/LuaTelemetry#175]
### Describe the bug

First of all REALY GOOD JOB with this script!!!

But at the moment i have a "little" problem.
The Telemetry start correctly but if i want to change the settings vie pressing "menu", then i cant Navigate with the Rotary Wheel from my Taranis x9e. I also cant use the Wheel to switch the telemetry view. 
The datas that are displayed are all correct.
In my OpenTX menus everything works normal.

I dont know excactly what for information you need to help me. If you need more i  will give it to you fast.

### Aditional context

Firmware OpenTX 9xe Version 2.2.2  10.08.2018

**Comment by teckel12** [comment]
@Peschi90 Interesting catch! The x9e must have slightly different event values for the rotary wheel compared to other Taranis transmitters. 

I'll look into this, should be an easy fix due to the way the control events are programmed. Expect a fix in v1.4.2 which I plan to release this Sunday.

**Comment by Peschi90** [comment]
perfect! i will test it after release
Thanks for the fast reply

edit: i meen the opentx **x9e** not 9xe in my first post.

**Comment by teckel12** [comment]
@Peschi90 Try the latest development build, it should now work on the X9E transmitter.  Instructions for upgrading here:

https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build

**Comment by Peschi90** [comment]
Thank you very much! with the development Build it worked for me!!
