### ISSUE TITLE
Not showing satellite count

### ISSUE THREAD

**Issue by skorokithakis** [teckel12/LuaTelemetry#176]
The telemetry screen is always showing 0 for the satellite count. My `Temp2` sensor is showing `3208` and there are 8 satellites coming from the GPS, but the telemetry screen shows 0. I am using a Taranis QX7 and RSS/batt/compass is showing up okay.

I haven't tried taking it somewhere with more of the sky visible to see if that fixes it, since I just installed the GPS, but shouldn't I be seeing the correct satellite count?

**Comment by teckel12** [comment]
@skorokithakis Strange... It should show the satellite count even before there's a GPS fix. What view are you using? Pilot or default? What version INAV and Lua Telemetry?

**Comment by skorokithakis** [comment]
I tried again today and it started showing satellites (which is odd, because I didn't do anything differently). It had 12 satellites but showed "NO GPS FIX". I am not sure which view I'm using, so i guess default. I'm using iNav 2.0.0 and possibly 1.4.0 of LuaTelemetry (where can I see that?).

**Comment by skorokithakis** [comment]
Sorry, I was using 1.3.1. Will upgrade now.

**Comment by skorokithakis** [comment]
Everything works with the latest version, thanks and sorry to have wasted your time!

**Comment by teckel12** [comment]
@skorokithakis Ah yes! Older versions of Lua Telemetry won't work well with INAV 2.0.0+ as the GPS signal quality indication totally changed, which Lua Telemetry uses to know when there's a GPS lock. 

Glad you figured it out and the latest Lua Telemetry resolves the issue.
