### ISSUE TITLE
Create radar view sample pics

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#189]

**Comment by vavisimo** [comment]
cant wait to see it :)

**Comment by teckel12** [comment]
@vavisimo It's now in the development branch, so you could not only see it but use it. Currently the orientation is launch-based, but adding top = north is trivial. A few small tweaks/additions are planned, but for the most part it's "finished".

**Comment by teckel12** [comment]
@vavisimo Here's a couple screenshots of the new radar view:
![inavqx7radar](https://user-images.githubusercontent.com/2592128/46053165-bcbd6880-c10f-11e8-89ab-db42e118447a.png)
![inavx9dradar](https://user-images.githubusercontent.com/2592128/46053166-bcbd6880-c10f-11e8-9d36-30ca995594c2.png)

**Comment by Peschi90** [comment]
That looks realy nice!! good job

**Comment by teckel12** [comment]
X9D radar view updated:

![inavx9dradar](https://user-images.githubusercontent.com/2592128/46114918-cfdd4080-c1c2-11e8-931b-9bb89773312e.png)

**Comment by teckel12** [comment]
@Peschi90 @vavisimo And a bit more UI polish...

![inavx9dradar](https://user-images.githubusercontent.com/2592128/46118243-8ea15c80-c1d3-11e8-918b-34ac3e9696c6.png)

I think I'm calling it done unless someone has any objections.
