### ISSUE TITLE
Add French support

### ISSUE THREAD

**Issue by d00bld0ze** [teckel12/LuaTelemetry#203]
### language translation file lang_fr.lua + fr wav folder

[lang_fr.lua + .wav.zip](https://github.com/iNavFlight/LuaTelemetry/files/2501474/lang_fr.lua.%2B.wav.zip)
Unzip to SCRIPTS/TELEMETRY/INav
A décompresser dans SCRIPTS/TELEMETRY/INav
### Partially tested / Partiellement testé
-Need other French speaking feedback for the translation of some words
-Besoin du feedback d'autre personnes parlant français pour la traduction de certains termes

**Comment by teckel12** [comment]
@d00bld0ze Thanks!  Will check into this once (and if) Github starts working again.

**Comment by teckel12** [comment]
@d00bld0ze See #206

**Comment by teckel12** [comment]
@d00bld0ze French language support was added to the development build.  To upgrade, follow the [Upgrade to Development Build](https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build) instructions.  If you could test and report back that would be great so I can get v1.4.3 released.  Thanks!

**Comment by teckel12** [comment]
Added in v1.4.3 release https://github.com/iNavFlight/LuaTelemetry/releases/tag/1.4.3
