### ISSUE TITLE
Add spanish support  

### ISSUE THREAD

**Issue by fmartinezo** [teckel12/LuaTelemetry#207]
### Describe the solution you'd like

[lang_es.lua.txt](https://github.com/iNavFlight/LuaTelemetry/files/2568420/lang_es.lua.txt)
[es-taranis.zip](https://github.com/iNavFlight/LuaTelemetry/files/2568422/es-taranis.zip)

**Comment by fmartinezo** [comment]
This is a feature request to add spanish language. I enclose lang.es.lua and one zip with all voices

**Comment by teckel12** [comment]
@fmartinezo Awesome! Will add this later today or tomorrow.

**Comment by fmartinezo** [comment]
Double check file lang_es_lua.txt I dot know lua and it is a copy of lua.de translated to spanish.Some terms in the voices and the text I have left in English because they are shorter and their translation into Spanish is complicated to express with a single or two words and are terms well known by aeromodelists. Pej "waypoint", "poshold", etc

**Comment by teckel12** [comment]
@fmartinezo See #208

**Comment by teckel12** [comment]
@fmartinezo Spanish language support was added to the development build.  To upgrade, follow the [Upgrade to Development Build](https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build) instructions.  If you could test and report back that would be great so I can get v1.4.3 released.  Thanks!

**Comment by fmartinezo** [comment]
@teckel12 Tested it and it workes good. Only one question. I have my taranis in spanish mode and lua select automatic spanish lenguage is it ok? or you can change it in lua in order to speak other lenguages i cant found this parameter. So if it is not possibe  it works great for me

**Comment by fmartinezo** [comment]
Very very very good work. Thanks so much

**Comment by teckel12** [comment]
@fmartinezo Lua Telemetry uses the Taranis settings for language. There's no language settings in Lua Telemetry at all. I have a Wiki document on how to setup your Taranis for different languages. 

https://github.com/iNavFlight/LuaTelemetry/wiki/Multilingual-Support

**Comment by teckel12** [comment]
Added in v1.4.3 release https://github.com/iNavFlight/LuaTelemetry/releases/tag/1.4.3

**Comment by fmartinezo** [comment]
@teckel12 New spanish voices less robotics and less metalic

[es.zip](https://github.com/iNavFlight/LuaTelemetry/files/2669843/es.zip)

**Comment by teckel12** [comment]
@fmartinezo I'll update these later today. Thanks!

**Comment by teckel12** [comment]
@fmartinezo The ZIP file seems to be corrupt.  At least I can't open it.

**Comment by fmartinezo** [comment]
Change "Zip" by "rar"

**Comment by fmartinezo** [comment]
@teckel12 I enclose new zip file
[es.zip](https://github.com/iNavFlight/LuaTelemetry/files/2677155/es.zip)
the previous file was compressed with winrar. This is compressed with winzip

**Comment by teckel12** [comment]
@fmartinezo Got it!
