### ISSUE TITLE
Display for KPH crops speed.

### ISSUE THREAD

**Issue by pkerney** [teckel12/LuaTelemetry#213]
When using km/h with the display on a Taranis X9D the actual speed is cropped to the point you can't see the most significant digit. km/h has an extra character and with 1 decimal digit as well you can't see the speed.
I tried setting the precision value in the telemetry screen to 0.-- but that didn't help.
Do you need one decimal point value for speed? Accuracy to that level is possibly not required. 
Probably and issue over 99.9MPH as well based on screen shots I've seen. 
Looks like only an issue on the Radar mode.

**Comment by teckel12** [comment]
@pkerney I'll look into it. It "should" remove a digit, but I don't test it in km/h often. I may just make it `kmh` so there doesn't need to be two different rules for metric and imperial.
