### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#214]
@Peschi90 Due to adding support for Horus transmitters, new German translations would be helpful:

### Max 10 characters
Fuel
Battery
Current
Altitude
Distance

**Comment by teckel12** [comment]
I'll take a stab at it:

Fuel = Kapazitaet
Battery = Batterie
Current = Ampere / Strom?
Altitude = Hoehe
Distance = Entfernung

I've learned the best way to get a reply on the Internet is not to ask for help but instead post something that's incorrect 😁

**Comment by Peschi90** [comment]
Sorry mate i saw it to late.
Your Translation is correct current means Strom in German Ampere is the value like Meter or miles. 

Great Job!

**Comment by teckel12** [comment]
@Peschi90 No problem, I didn't need the answer quickly, just attempting to make it easier.
