### ISSUE TITLE
bad argument #6 on 1.5.0 with QX7

### ISSUE THREAD

**Issue by Xedos9er** [teckel12/LuaTelemetry#233]
### Describe the bug
when starting Lua telemetry I´m getting bad argument #6 on my qx7

### To reproduce

1. start lua script with page button
2. see error "bad argument #6"

### Radio and model settings
QX7 latest OpenTX nightly N685, R9M + R9MM running latest flex firmware

### Additional context
1.4.1 works without issues

**Comment by Xedos9er** [comment]
yes, developmendt build works fine

**Comment by teckel12** [comment]
@Xedos9er :+1:
