### ISSUE TITLE
CRSF: Show transmitter power `TPWR` instead of GPS alt

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#237]
Crossfire doesn't get the GPS altitude so it can't be displayed. But, transmitter power (in mW) would be useful information.

Remove GPS altitude from all views and replace with transmitter power when using Crossfire. 

* [x] Horus
* [x] Taranis classic view
* [x] Taranis pilot view
* [x] Taranis map view

**Comment by KnuckleUpFPV** [comment]
So the alt sensor I get is only from the barometer?

**Comment by teckel12** [comment]
@KnuckleUpFPV  S.Port telemetry outputs two altitude sensors.  GPS altitude and altitude compared to launch.  Crossfire only outputs one altitude sensor, which isn't altitude above sea level like GPS altitude shows.  This is the extra thing that can't be displayed on Crossfire as it doesn't output that value.  

Altitude is still being shown on Crossfire.  INAV uses the barometer first for altitude as it's more accurate.  If the barometer doesn't exist, it uses the GPS altitude and compares that to launch altitude.  Still, only one altitude value is sent via Crossfire (altitude above launch position).  It never gets GPS altitude above sea level so that value can't be displayed (the reason for this issue).

**Comment by KnuckleUpFPV** [comment]
If crossfire is being fed altitude from inav. And inav just added an above sea level altitude, wouldnt that be able to be used as opposed to the above ground level from takeoff?

**Comment by teckel12** [comment]
@KnuckleUpFPV INAV has always had an above sea level altitude (sent from the GPS and barometer). I think what you're referring to being added was showing this on OSD? 

It was TBS's decision to transfer relative to launch altitude. Most people want relative altitude so that's the telemetry value Crossfire is sending. Crossfire would need to add altitude above sea level, before INAV and Lua Telemetry could accomidate it.

I live in northwest Ohio, US, so altitude above sea level is irrelevant (I only use the GPS altitude to get a better idea of how good the GPS lock is).

**Comment by KnuckleUpFPV** [comment]
Yeah was unaware of it reporting above sea level. I've only ever seen above ground level on takeoff.

**Comment by KnuckleUpFPV** [comment]
I will ask remo if he can add altitude above sea level.
