### ISSUE TITLE
Make compatible with Betaflight/Crossfire

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#248]
> To be clear, Betaflight already works with Lua Telemetry when using S.Port telemetry (and probably F.Port as well).  This is for supporting Crossfire telemetry when running Betaflight.

Fairly simple to do, nothing really needs to be changed with Lua Telemetry (did add `STAB` as Betaflight is still using `ANGL` sometimes and `STAB` other times, but all flight modes include stability, including `ACRO`. I know, confusing, which is why it should be called `ANGL`):

https://github.com/betaflight/betaflight/pull/7495

But getting unit testing errors, no idea why as I can't do unit tests locally for some reason.  Anyone have experience with unit tests?

**Comment by teckel12** [comment]
While the change is simple, getting the unit tests to pass in Betaflight is problematic.  If someone wants Lua Telemetry to work in Betaflight with Crosfire, here's the code changes:

https://github.com/teckel12/betaflight/pull/1/files

It compiles just fine, but there's something causing an error in the unit test.  @mikeller gives some guidance in the following message as to what needs to be setup to get unit testing to work:

https://github.com/betaflight/betaflight/pull/7495#issuecomment-458399610

If this interests someone, the information is there.  I just don't have the time to learn these systems just for Betaflight when I'll probably never use Betaflight with Crossfire anyway.

**Comment by mikeller** [comment]
@teckel12: Done: https://github.com/betaflight/betaflight/pull/7495/commits/bece287cc45bee318266e380bda9d1d5ccac4837

**Comment by teckel12** [comment]
@mikeller The logic changes and reductions in mode status renders it no longer capable of doing what it was intended.

**Comment by mikeller** [comment]
@teckel12: Can you specify what was intended?

All I did was to reorder the stati to match the importance of the modes in Betaflight - there seems to be no point in not showing the flight mode before arming - once flying, the pilot will know if they are in acro or a stabilised mode, but if they arm in the wrong mode, then they are probably going to crash. Also, not showing a failsafe after the failsafe has disarmed the craft seems to be misleading.

**Comment by teckel12** [comment]
@mikeller I made the changes for you to review.  I tried to keep the same spirit of the order of the flight modes.  But, I did need to reorder the non-flight modes to show the armed/unarmed status or errors when appropriate.

Without the `OK` status showing "Ready to be armed" is critical to know the armed/unarmed state.

I agree with the `!FS!`, I'll move it outside the ARMED condition.

**Comment by teckel12** [comment]
Come to find out, this does not make sense at all in Betaflight.

From Betaflight:
> A craft is always ready to arm, unless isArmingDisabled() is true. So the pilot can assume that unless they get !ERR the craft is ready to arm. There is no point in withholding safety relevant flight mode information just to send a meaningless status.

So, adding support for Crossfire in Betaflight won't be possible after all.  However, if using Betaflight and S.Port telemetry Lua Telemetry still works.

**Comment by teckel12** [comment]
Betaflight won't have the ready to arm `OK` flight mode. But, when unarmed it adds a `*` to the end of the flight mode.

For example, unarmed angle flight mode will be `STAB*` with Betaflight.

Have code look for an `*` and set arming status accordingly.
