### ISSUE TITLE
Option to change altitude alert mode from max to current

### ISSUE THREAD

**Issue by wx4cb** [teckel12/LuaTelemetry#256]
Is it possible to change the altitude alert to only sound if you're higher than the max alt you have set?

Reason why is once you reach max alt (400 for me :P) even if you are then < than that altitude it still sounds. for example I was testing climb performance of my S1100 while testing different props and  I was at 600 feet in class G airspace, obviously the alert is set for 400 but when i got down to 200 feet it was still reading the 600 foot altitude. so of course reading out ~600 ft altitude when i'm at 150 is a bit distracting :D

Next time i try it, i'll try and record a video to give more information, but basically it kept reading out the max altitude and not the altitude i was at or even stopped once i got below the alert altitude set.

I would be nice to be able to have an option in the config to set it to alert at all altitudes (ie verbal altitude readout) or only say your altitude if you are above the max set.

Hope that makes sense.

**Comment by teckel12** [comment]
@wx4cb I'm not following you.  It should only show the current altitude and the alert beep and/or feedback should only sound when you're over the set max altitude.  For example, you can set the max altitude to 600 feet and it should only alert you when you're over 600 feet.  Once you go below 600 feet the alert stops.

**Comment by teckel12** [comment]
@wx4cb I just verified that it only gives the alerts (flashing/color change, beeps or/or altitude announcements) when over the max altitude set.  Once you go below the max altitude it stops reporting/beeping/flashing/color changes as it should.  It also only shows your current altitude.  The only time it can show your maximum altitude is when disarmed (can't show min/max values while flying).

Maybe you have the `Variometer` option set to `Voice`?  If so, this is designed to always voice report your altitude, which has nothing to do with the max altitude set.  It's designed for fixed wing pilots.  With this setting, there's the accompanying `Vario Steps` which allows you to set the increments when the altitude change is alerted.  For example, if set to 50 feet, it will announce every time you climb or descend by 50 feet.

**Comment by wx4cb** [comment]
let me double check those and get back to you. won't be for a couple days though, out of town

**Comment by wx4cb** [comment]
ok just got around to getting back to this. variometer is off, but once i hit 400 feet and go back down, it still says the max height. also, just as a test, i went up to 700 feet and when i went back down it still was saying that the rest of the flight.

Am I missing something here in the configuration?

![20190501_174110](https://user-images.githubusercontent.com/1495297/57044534-db9d5380-6c38-11e9-8858-fb897097640f.jpg)
![20190501_174036](https://user-images.githubusercontent.com/1495297/57044535-dc35ea00-6c38-11e9-8fef-0d04c4725d72.jpg)
![20190501_174046](https://user-images.githubusercontent.com/1495297/57044536-dc35ea00-6c38-11e9-8136-bec6c2447caa.jpg)
![20190501_174103](https://user-images.githubusercontent.com/1495297/57044537-dc35ea00-6c38-11e9-8a2e-6232d6ac48d4.jpg)

**Comment by teckel12** [comment]
@wx4cb Better than pics would be the .dat file for the model in question. See the cfg folder inside the iNav folder.

**Comment by teckel12** [comment]
@wx4cb I tried it with the latest development build and the best I could duplicate your config settings without the cfg file and it seems to work just fine. It beeps, announces the altitude and the altitude flashes when 400' or higher. As soon as I drop belop 400' the flashing, beeping, and voice accouncements all stop. Tried several times, always worked correctly. Went up to 700' with the same result.

Make sure you're using the latest development build and if you're still having problems I'll need the cfg .dat file and your telemetry logs to simulate your flight.

**Comment by teckel12** [comment]
Do you happen to not have a barometer? Does it show the correct altitude on the display?

You say it was "still reading the max altitude". What do you mean by that? I thought you meant that it was voice  announcing your altulitude. But now that I read what you posted again, maybe what your trying to say is that the display still shows the max altitude? Does this have anything to do with the voice announcements "reading" you your altitude or do you mean the display is showing the max altitude.

Confused by your choice of the word "reading".

**Comment by wx4cb** [comment]
No i have barometer (f722 wing) and just tried it, unable to get latest dev release but its on latest public. Whats your email address so i can send you all this stuff.
