### ISSUE TITLE
Incorrect cell number detection with high voltage cells

### ISSUE THREAD

**Issue by expipiplus1** [teckel12/LuaTelemetry#258]
### Describe the bug

Cell number detection is hard coded to 4.3V,  some high voltage lipo cells can be charged to 4.35V. This manifests itself as an incorrect better level bar in the widget, and spurious low battery warnings.

It's worth noting that inav has configuration parameters for the cell count detection threshold and allows for an explicit number of cells.

### To reproduce

Use the widget with a model with a fully charged lipo hv battery. Observe that the battery bar is near empty and low battery messages are played.

### Expected behavior

The number of cells is detected correctly

**Comment by expipiplus1** [comment]
For reference, the battery detection code is here: https://github.com/iNavFlight/LuaTelemetry/blob/master/src/iNav.lua#L131-L132

**Comment by teckel12** [comment]
@expipiplus1 I've had this happen as well. I'll look into it today. Seems like an easy fix/enhancement.

**Comment by teckel12** [comment]
@expipiplus1 As a side note, this cell count calculation is a backup for the cell voltage on the `A4` telemetry sensor. I didn't realize that was yet another sensor missing from Crossfire telemetry (there are many things missing). So this is really only a problem with Crossfire telemetry, not any FrSky telemetry which includes the `A4` cell voltage sensor, I believe for both INAV and Betaflight.

**Comment by expipiplus1** [comment]
Thanks for looking at this!

**Comment by teckel12** [comment]
@expipiplus1 I just realized that I didn't note in this issue that the enhancement is included in the latest development branch. There's now a config menu option that allows you to set the max cell voltage for cell count calculation named `Cell Calculation`. It defaults to 4.3V for LiPo but you can set this to 4.4V for LiHV.

**Comment by expipiplus1** [comment]
Cool, thanks again.
