### ISSUE TITLE
Works with SmartPort not FrSky telemetry

### ISSUE THREAD

**Issue by SPlissken** [teckel12/LuaTelemetry#26]
This currently only works with FrSky S.Port telemetry and will not work as is with 'original' FrSky telemetry.
It's not a problem but the README.md suggests that it might: "A FrSky receiver that supports telemetry,"
Although the listed receivers support SmartPort other FrSky receivers that support telemetry such as D4R-II don't support SmartPort and therefore don't work with this otherwise excellent script.

**Comment by DzikuVx** [comment]
@teckel12 I suggest stating in README that SmartPort is required and will not work with D-series receivers

**Comment by teckel12** [comment]
Addressed in #27
