### ISSUE TITLE
Option to reverse artificial horizon roll

### ISSUE THREAD

**Issue by Stringbrakr** [teckel12/LuaTelemetry#269]
### Is your feature request related to a problem? Please describe.
I wish to reverse the artificial horizon roll

### Describe the solution you'd like
When I bank right, have the horizon bank right as well.

### Additional context
Thank you very much. This can be a real airplane saver for me. The page with the ADI helps me the most. I am having a problem to solve. the roll indicator is reversed on my taranis 9d+. the command in the inav cli has the set osd_artificial_horizon_reverse_roll = ON it works on the osd but it does not change the lua ADI. Any ideas?

**Comment by Stringbrakr** [comment]
Thank you very much. This can be a real airplane saver for me. The page with the ADI helps me the most. I am having a problem to solve. the roll indicator is reversed on my taranis 9d+. the command in the inav cli has the set osd_artificial_horizon_reverse_roll = ON it works on the osd but it does not change the lua ADI. Any ideas?

**Comment by teckel12** [comment]
@Stringbrakr First, the transmitter doesn't see the INAV settings, so it's not correct to assume that a setting in INAV will be sent to the transmitter, it absolutely does not.

Secondly, I have no idea what you mean or what your request is.

**Comment by teckel12** [comment]
@Stringbrakr Okay, I think I may be understanding you.  You're looking at it as an attitude indicator and not an artificial horizon.  A Russian attitude indicator keeps the horizon horizontal and moves a plane indicator to show attitude.  That's not what the artificial horizon shows.  It shows the horizon angle.  There's no ability to rotate the plane indicator to show attitude in relation to a fixed horizontal horizon.

**Comment by Stringbrakr** [comment]
Thank you.  I knew that I had to be doing something wrong.  I just didn't know I was misunderstanding its  basic function.
