### ISSUE TITLE
CRSF Arm status not working

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#27]
First of all, great to see you back here @teckel12 !
Can you please add the mentioned fix to the code.

See: https://github.com/iNavFlight/LuaTelemetry/issues/396#issuecomment-782928916

**Comment by teckel12** [comment]
Cross-references:

https://github.com/iNavFlight/LuaTelemetry/issues/396#issuecomment-782928916

https://github.com/iNavFlight/LuaTelemetry/issues/441

**Comment by teckel12** [comment]
@Xedos9er Will include in 1.8.0

**Comment by Xedos9er** [comment]
Thanks, take into account that maybe Frsky is also suffering from this issue.

**Comment by teckel12** [comment]
@Xedos9er It wouldn't be, as the flight mode logic works totally different with FrSky telemetry.  With FrSky, airmode is just reported as acro I believe.
