### ISSUE TITLE
RSSI display issue

### ISSUE THREAD

**Issue by frouxel** [teckel12/LuaTelemetry#272]
Hello,

I'am discovering INAV and all job that has been done around this project, it is very interesting.
Here is my configuration : Matek F722STD + Matek M8Q-5883 GPS + INAV 2.10 + FRSKY R-XSR with FPORT 2019 EU-LBT Firmware connected on TX2 + Taranis X9d Plus EU under OpenTx 2.2.3 + INAV 1.61 LUATelemetry.

I have followed installation instructions and Telemetry on FPORT works well.
The only issue I have discovered is that RSSI value is alive in classic view but it is stuck to 99dB in pilot and radar views.

Should the value be the same between views ?
Is there something I can test/check to investigate the issue ?

PS : Sorry for my poor english
Regards,

**Comment by teckel12** [comment]
@frouxel Never heard of this problem, could only guess what the solution could be.

Please open another issue, select `bug` and follow the template and instructions provided that I need to look at and solve your issue.

https://github.com/iNavFlight/LuaTelemetry/wiki/Issue-Template
