### ISSUE TITLE
Lua disable when selected on boot up of TX

### ISSUE THREAD

**Issue by jm-wijnholds** [teckel12/LuaTelemetry#275]
i've found a problem with the latest version of the iNav LuaTelemetry:

When using it on an Horus X10(s) you can not boot you TX with this lua script enabled otherwise it will tel you that it is disabled. A little research gave me this error: "refresh():?:0: attempt to compare number with nil"

What does work is making second screen: one with the lua widget, and another one without the lua. Shutdown the tx with the screen without the lua(so the tx will bootup in this screen when you turn it on), en than go to the screen with the lua widget.

In multiple FB groups i found people having the same issue.

I'm using version: v1.6.1 from lua and OpenTX version 2.2.3 on an Frsky Horus X10s. (for the record, the screen with the lua is full screen, without the top bar and trims. Also running only one screen does not help)
![57572770_819788308357823_8719350275980132352_o](https://user-images.githubusercontent.com/8899068/56467262-eed04800-641c-11e9-8b1e-3e707c72ab61.jpg)

**Comment by teckel12** [comment]
@jm-wijnholds I assume these FB groups are not specific to this Lua Telemetry script but to lua in general? Sounds like an OpenTX bug?

**Comment by teckel12** [comment]
Fix merged into development.

**Comment by jm-wijnholds** [comment]
Hi Teckel, No the FB groups were specific in this Lua Telemetry Script :). It was also mentioned that it was working on version 1.5.1 and was 'broken' in from version 1.6.

but i see that you've added a fix for it. Will try version 1.6.2 when its out. thanks!

**Comment by teckel12** [comment]
@jm-wijnholds Yes, someone else reported the same thing and I believe v1.6.2 fixes it.

**Comment by teckel12** [comment]
@jm-wijnholds Not sure why there would be groups in a vacuum on FB when they could be communicating directly with the author on Github or Telegram.

I know some are comfortable with FB, but it's not designed for issue tracking. Please encourage those with issues to use the Github issue system. Or, for real-time chat, Telegram works really well. Both are listed in my Wikis.

If they want mobile apps for support, FastHub is a good Github app for mobile and the native Telegram app works great.
