### ISSUE TITLE
If run the Lua script in a widget,I can not flip between compass-based and launch/pilot-based orientation and radar with the dial or +/- buttons

### ISSUE THREAD

**Issue by 87040109qq** [teckel12/LuaTelemetry#280]
If run the Lua script in a widget,I just can not flip between compass-based and launch/pilot-based orientation and radar with the dial or +/- buttons.
But if I run LUA script  from SD card directly ,the dial works!
Is that a bug?
my sets:
horus x10s opentx 2.2.3   lua 1.6.2

**Comment by 87040109qq** [comment]
If there is a text note indicate what mode have been selected show on the screen  when flip between different mode would be great.

**Comment by 87040109qq** [comment]
If can not flip between different mode in widget ,add a menu option  may be good ideal or flip with stick before armed.

**Comment by teckel12** [comment]
@87040109qq That's correct. You can't do that in a widget. The reason is that OpenTX has (for some reason and on purpose) blocked all non-flight controls from being monitored on Horus when running scripts as a widget. This is why the config menu can only be accessed while not armed and uses the sticks for navigation.

At some point (if OpenTX comes to their senses and removes the purposeful blocking of non-flight controls to widgets) that feature will be available. But currently, it's not, 100% due to an OpenTX decision.

**Comment by teckel12** [comment]
@87040109qq Every config menu option takes a surprising amount of memory, which not much is available. When not armed, the stick toggles the min/max or current values.

The real solution to this is for OpenTX to allow widgets to see non-flight controls. There's not really a good reason why they block it anyway.

**Comment by teckel12** [comment]
@87040109qq Here's the OpenTX issue for exposing key events to widgets on the Horus:  https://github.com/opentx/opentx/issues/3821

It seems that a UI refactoring is happening with OpenTX which will resolve this issue.  So, this issue will be resolved at that time.  I'll try to come up with another solution in the meantime.

**Comment by 87040109qq** [comment]
OK！ just wait for the time.

**Comment by teckel12** [comment]
@87040109qq Latest development build adds a option for a preferences file `prefs.dat` in the `cfg` folder.  In the `prefs.dat` file you can specify your default model orientation.  See #288 for details.

For you, you probably want your `prefs.dat` to be `011`, unless you also want to try one of the new aircraft symbols (which you select with the first digit, currently `0`).

**Comment by teckel12** [comment]
BTW: Global preferences have been deprecated and incorporated in the config menu due to memory enhancements from refactoring #289.  Please see the [config menu](https://github.com/iNavFlight/LuaTelemetry/wiki/Configuration-Settings) to set these options.
