### ISSUE TITLE
Fuel percent on Crossfire showed negative values

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#285]
Shows negative fuel instead of fuel remaining.

**Comment by teckel12** [comment]
https://github.com/iNavFlight/LuaTelemetry/pull/274/commits/804107ecb5202fa79f8266b0631285f768bf4fa0

Fix merged into development branch

**Comment by teckel12** [comment]
I couldn't duplicate so this must be an edge case problem (or I was switching batteries as it was only happening on the bench).  I made a change which should prevent negative fuel values.

**Comment by Jetrell** [comment]
Can't say I've seen it happen Tim. But thanks for the edge case fix.
