### ISSUE TITLE
Replace the green background with the google map 

### ISSUE THREAD

**Issue by 87040109qq** [teckel12/LuaTelemetry#286]
If the  subsequent   LuaTelemetry release could  replacing the green background with the google map fetched with the mission planner ,so the piolt knows the location of the modle on the map.If it does, that would be great ! 
Does  the horus‘s hardware  support this idea?

**Comment by wx4cb** [comment]
it would be highly unlikely that you could do a google map. you would need to store the tiles on the radio itself or be able to generate them on the fly, then of course there's the memory issue.

**Comment by teckel12** [comment]
@87040109qq Would be uber-cool, but basically impossible due to map image file sizes, slow screen rendering speed, slow SD card access, lack of internet connectivity, etc.
