### ISSUE TITLE
Additional aircraft symbols on attitude indicator for Horus

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#287]
### Is your feature request related to a problem? Please describe.
Current aircraft symbol is boeing! (meant to be a pun, say it like "boring")

### Describe the solution you'd like
Option to switch aircraft symbols

### Describe alternatives you've considered
Dealing with it

### Additional context
Here's the current options I've put together:

![AircraftSymbols](https://user-images.githubusercontent.com/2592128/57571057-193b7280-73d7-11e9-87a9-629235176b71.png)

I was going to try and name them, but having a hard time.  The current one (first one in the pic) would be the `Boeing`, the next would be `Classic` maybe?  The next two would be `Garmin1` and `Garmin2`, while the second to last (plane) would be `Dynon`.  The last one is really troubling, I can find no name for this type of aircraft symbol, so I'm calling it `W` till someone tells me otherwise.

But, if I've made a mistake in my current naming, let me know.  I asked an actual pilot friend of mine and he had no idea what the different types of aircraft symbols were named.  Maybe I'm just too much a stickler for details being right.

Thoughts, opinions?

**Comment by wx4cb** [comment]
The last one is just a level flight and bank indicator combined. The slants are usually at 20 degrees iirc.

 the ‘W’ symbol is called the Waterline symbol and represents the point at infinity where the longitudinal axis of the aircraft points toward. It is analogous to the miniature airplane symbol on an attitude indicator. A similar symbol called the Gun Cross is used on the F-16 HUD.
On high performance aircraft capable of high AoA operations, the waterline symbol is not as useful as the Flight Path Marker or Velocity Vector symbol which indicates the point at infinity the aircraft is currently trending towards. The dot or circle i mention below


2nd to last is usuallt a dual indicator with the circle and lines split horizon line and flight path indicator where the circle represents the actual path of the aircraft as you could be level but be descending like in a flat stall. Same for the Boeing and the airbus ones that are 1st/2nd. 

A

**Comment by teckel12** [comment]
@wx4cb For sure, the aircraft symbols are not sophisticated like commercial-grade glass cockpits.  It's meant to be more of a style option as they're all fixed in place.  Eventually, I'd really like to incorporate indication of orientation vs. flight direction as well as wind speed (or at least direction).  INAV is dabbling with these now, although I need to verify if Crossfire is already technically supplying orientation vs. flight direction.  With orientation vs. flight direction, it's possible that I could calculate wind direction.  I only fly quads, so it may be a bit of stretch for me as it's really irrelevant.

Anyway, it seems naming the last one `Waterline` seems like a good move.  The second one I see in "classic" attitude indicators, I know it's used in other cases, but would `Classic` be a good name?  Should I remove the second to last as it would be confusing, especially if  we later have additional telemetry which could indicate flight path vs orientation?

**Comment by wx4cb** [comment]
crossfire telemetry has rotation - by default in rads but can be set to degrees (Ptch/Roll/Yaw) so obviously if your roll > 100 degrees you're almost upside down etc

**Comment by wx4cb** [comment]
as far as the icons... personally I find the waterline too big.... but i'm used to having just a dot or the 2nd to last one for the middle. maybe keep them as the same ones you can use in inav might be the way to go?

**Comment by teckel12** [comment]
@wx4cb I made the Waterline aircraft symbol a bit thinner.  INAV is character based and B&W, so it would be limiting to copy INAV.

**Comment by wx4cb** [comment]
> @wx4cb I made the Waterline aircraft symbol a bit thinner. INAV is character based and B&W, so it would be limiting to copy INAV.

no what I meant was, copy the designs that are on there so people can use the same ones on the osd, on the radio.

**Comment by teckel12** [comment]
@wx4cb Is there a web page which outlines the aircraft symbols in INAV OSD?

**Comment by teckel12** [comment]
BTW, I've added multiple aircraft symbols to the development branch.

**Comment by teckel12** [comment]
![AircraftSymbols](https://user-images.githubusercontent.com/2592128/57576212-4ebc7c00-7428-11e9-928f-126c49aed679.png)

**Comment by wx4cb** [comment]
i would guess it would be referenced some how by

OSD_CROSSHAIRS

typedef enum {
    OSD_CROSSHAIRS_STYLE_DEFAULT,
    OSD_CROSSHAIRS_STYLE_AIRCRAFT,
} osd_crosshairs_style_e;

^^ those are in osd.h in main/io there's no wiki pages in the configurator and no other mention in the main wiki.

**Comment by teckel12** [comment]
@wx4cb Those two I remember, I figured there was more that I wasn't privy to. As long as the ones I've shown here are not broken in some way I'll add them. We can always fix/extend later.

**Comment by wx4cb** [comment]
there were more in the development version, oliverC was working on some and then that got pulled in favour of the lora thing.

**Comment by teckel12** [comment]
@wx4cb That must have been what I was thinking of. I'll look around.
