### ISSUE TITLE
Create preferences file for basic style options that wouldn't change per-model

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#288]
@87040109qq Regarding #284 I've been giving this "Preferences" some consideration and thought today.  Maybe certain options could be done in a preferences file instead of the in-script configuration menu?

Looking through the existing config menu, I feel that almost all are on a per-model basis.  Sure, you may have every model set the same, but I could also see someone wanting something different for a particular model.  The only exception is "GPS Coordinates", which is a user preference that wouldn't change model to model.  Actually, now that I think of it, why would anyone want GPS coordinates in decimal?  Seems more of a legacy thing that's leftover from the first release of Lua Telemetry that no one really wants.

What I'm considering is a `pref.dat` file that a user could use to specify particular preferences.  The 3 and maybe 4 preferences I have in mind are:

Aircraft symbol (0-5)
Fixed home position (0/1)
Default craft orientation (0=launch/pilot-based, 1=compass-based)
GPS coordinates (0=deg/min, 1=decimal)  - Is this even needed?  Doesn't everyone want deg/min?

The thought is that everything defaults to the zero options (of if the file doesn't exist it would default to the zero options).  But, the user could create a `pref.dat` file with contents like `5111` which would set the user's preference.  This would also allow additional features to be added without using much memory.

Thoughts?

**Comment by teckel12** [comment]
Latest development build adds an optional global preferences file `prefs.dat` in the `cfg` folder.  The file allows you to set certain features globally to your own preference.  It currently supports 3 settings (each one digit so 3 digits long).  The 3 settings are as follows:

1. Aircraft symbol (Horus only): **0** = Boeing/Airbus (default), **1** = Classic, **2** = Garmin1, **3** = Garmin2, **4** = Dynon, **5** = Waterline
2. Radar home position (Horus only): **0** = Adjust to fit (default), **1** = Fixed in center
3. Default orientation: **0** = Launch/pilot-based (default), **1** = Compass-based

Example: `prefs.dat` with the content: `511` would use the waterline aircraft symbol, fix home position to the center in the radar view, and make the default orientation compass-based.  All options default to `0` so if the file doesn't exist or doesn't have enough digits it will use the default option.

**Comment by 87040109qq** [comment]
Thanks for your great idea! Now we can  select home positon through prefs.dat ！
BTW Does the widget can read the " global variable" which could turned in open tx ,mybe it works?

**Comment by teckel12** [comment]
@87040109qq Not sure what your question is referring to.

**Comment by teckel12** [comment]
BTW: Global preferences have been deprecated and incorporated in the config menu due to memory enhancements from refactoring #289.  Please see the [config menu](https://github.com/iNavFlight/LuaTelemetry/wiki/Configuration-Settings) to set these options.
