### ISSUE TITLE
Specify stick mode for Horus settings in wiki

### ISSUE THREAD

**Issue by nmaggioni** [teckel12/LuaTelemetry#293]
The [Configurations Settings](https://github.com/iNavFlight/LuaTelemetry/wiki/Configuration-Settings) page should mention that the Horus' stick commands show Mode 2 sticks.

**Comment by teckel12** [comment]
@nmaggioni Sounds reasonable. I'm really hoping OpenTX releases their UI update that includes widgets being able to "listen" to key events so the current nonsense needed for thr config menu can just be removed.

**Comment by teckel12** [comment]
Done
