### ISSUE TITLE
T16: Setting fuel percent causing disabled script

### ISSUE THREAD

**Issue by wx4cb** [teckel12/LuaTelemetry#300]
Latest dev version, latest version of Jumper TX (2.2.3)

Changing the Fuel display in the config from "percent" to mAh causes the script to be disabled.

Reproduce: hard because you don't have a T16

Attached is the config file from the cfg folder. It's not actually a zip, just remove the extension.

[Mini Drak.dat.zip](https://github.com/iNavFlight/LuaTelemetry/files/3221563/Mini.Drak.dat.zip)

**Comment by teckel12** [comment]
@wx4cb This was resolved earlier today in the development branch. An upgrade should fix it.

**Comment by teckel12** [comment]
Added to v1.7.0
