### ISSUE TITLE
Horus: Preview airplane symbols in config menu

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#301]
### Is your feature request related to a problem? Please describe.
Hard to know what the airplane symbols look like till you change them.

### Describe the solution you'd like
Show what they look like as you change them.

### Describe alternatives you've considered
Living with the way it is now.

### Additional context
Maybe move the config menu to the left when on the Airplane Symbol option so a sample can be shown to the right?  I added code to show a preview at the bottom of the screen, but that no longer works after other changes were implemented. Should mostly be refactoring code.

**Comment by wx4cb** [comment]
I was wondering why they disappeared when i upgraded. Personally (and im guilty of this) just point people to the wiki, or at least use the name if you can and not a number, then point them to the wiki heh

**Comment by teckel12** [comment]
@wx4cb I had already written the code to show a preview, I just needed to tweak it a bit after other changes were made.  It's in the latest development branch now.
