### ISSUE TITLE
Update language file for new config menus

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#302]
### Is your feature request related to a problem? Please describe.
New config options added that need to be translated to other languages.

### Additional context
The following config menu items need translation (max 16 characters):
- Aircraft Symbol
- Center Map
- Default Orientation
- Roll Scale

And the following options need translation (max 8 characters):
- Launch
- Compass

Languages to translate:
- [ ] German
- [ ] Spanish
- [ ] French

**Comment by wx4cb** [comment]
I can help with german if you give me the English language text you want

**Comment by teckel12** [comment]
@wx4cb For the menu items there's a max of 16 characters.  For the options (Launch/Compass) the max is 8 characters.  Only the Orientation options need translation because the others are Yes/No or a number.

**Comment by teckel12** [comment]
I'm going to let Google Translator do this. Then if wrong someone can make a correction later.
