### ISSUE TITLE
OpenTX 2.2.4 LuaTelemerty 1.7.1

### ISSUE THREAD

**Issue by dsaboot** [teckel12/LuaTelemetry#334]
I've update Taranis QX7 to OpenTX 2.2.4
Update SD_card data to new one (delete all data before update)
Install LuaTelemetry 1.7.1
Only 1 lua script installed on my Taranis.
If I start script - "attempt to call a nil value"

I've also update to 2.2.4 my Horus X12S
And luaTelemetry 1.7.1 also didn't work on X12S - "disabled" error

At OpenTX 2.2.3 all was correct.

**Comment by teckel12** [comment]
@dsaboot Was this problem resolved?  If so, what was the solution?  Or, did you accidentally close the issue?

**Comment by dsaboot** [comment]
Problem solved.
I've flashed Q7X with other list option - luac, nooverridech, nogvars


>Четверг, 18 июля 2019, 18:45 +03:00 от Tim Eckel <notifications@github.com>:
>
>@dsaboot Was this problem resolved?  If so, what was the solution?  Or, did you accidentally close the issue?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,

dsaboot@mail.ru

**Comment by teckel12** [comment]
@dsaboot Ah yes!  v1.7.1 does require the `luac` build option.  The next release won't require `luac`.
