### ISSUE TITLE
Crossfire telemetry FM  !ERR

### ISSUE THREAD

**Issue by Jetrell** [teckel12/LuaTelemetry#341]
I vaguely remember reading something about this before. And am unsure if it has always been a problem with the X9D and CRSF.
Is this a Crossfire problem or LuaTelemetry ?

Thanks

![20190813_170811](https://user-images.githubusercontent.com/47995726/62921887-4ee46300-bded-11e9-883c-7a179cf40c23.jpg)

**Comment by wx4cb** [comment]
if it's in the opentx telemetry screen as that, then it's not a lua telemetry issue. that's what's being sent from the FC. Have you tried deleting all the sensors and rediscovering them?

**Comment by Jetrell** [comment]
> 
> 
> Have you tried deleting all the sensors and rediscovering them?

Yep, I have. But it still remains. Sometimes it will not be a problem and the FM telemetry will work correctly. Then other times, this appears.

**Comment by teckel12** [comment]
@Jetrell The `FM` (flight mode) sensor is coming directly from INAV, nothing to do with Lua Telemetry.

`FM` shows not only the flight mode (`ACRO` and `RTH` for example), but also the status.  There's 3 status values for `FM` other than flight modes:

- `OK` = Ready to arm
- `WAIT` = Waiting for GPS lock
- `!ERR` = Arming disabled

Basically, `!ERR` means INAV is reporting that arming is disabled, here's the code in INAV:

```
    } else if (isArmingDisabled()) {
        flightMode = "!ERR";
    }
```

**Comment by Jetrell** [comment]
That explains it. I got confused with seeing it in iNav and not with other flight software using CRSF. And I couldn't work out why it played up a few times in iNav as well. This left me wondering, At least I now know how it should act.
Thanks for the clarification Tim :-)
