### ISSUE TITLE
Taranis X9D Plus 2019 Edition

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#344]
Anyone have a 2019 version of the Taranis X9D Plus (the one with ACCESS) and can verify it works with Lua Telemetry?  I can't see why not, if anything it will run faster and allow multiple Lua scripts to run without memory issues (thanks FrSky!)

**Comment by wx4cb** [comment]
oh the access one. no i haven't done any of that. all my gear (what's left
of it) is ACCST

**Comment by omegat** [comment]
The script works but you can't change any menu items; the scrollwheel doesn't work. I don't know if its a general problem with OTX2.3 or with the SE2019.
I can also report that LuaTelemetry does eat up a lot of memory so the betaflight script to change the values does not work (not enough memory).

**Comment by teckel12** [comment]
@omegat It's possible that the model is identified differently so it doesn't know the controls. OpenTX is changing the control events in 2.3 to simplify things, but I don't think they removed the 2.2 and prior events (that would be bad). Going forward, the virtual events with 2.3 will simplify the code. But 2.3 isn't released for all transmitters, so I can't switch to this method yet.

**Comment by omegat** [comment]
@teckel12 the MENU, PAGE and EXIT buttons work fine. I can switch to the menu screen and select the first item by pressing the wheel. But the item does not change its value when turning the wheel. So I suspect that the wheel-turning events to be different from the button-pressing events. - Or as you said the transmitter identifies e.g. as a 'normal' X9D. However I wanted to update to the current Nightly 27, but that failed to compile. 
The ACCST (I don't have an ACCESS RX yet, and I can't upgrade my XSRs) telemetry values seem to work (have to test this further) though.

**Comment by teckel12** [comment]
@omegat Ah! It has a wheel! That's an easy fix. I should be able to sort that out quickly. I'll let you know.

**Comment by omegat** [comment]
.. yeah :D 
The wheel was the big selling point for me. In essence it should work like the X9 lite

**Comment by teckel12** [comment]
@omegat Merged to development.  If you haven't  run the development branch, it's as simple as this:

https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build

**Comment by omegat** [comment]
@teckel12 I'm sorry but no joy. I used the LuaTelemetry-development.zip -file from the wiki site you linked; the file was from today, 22:58. 
Tell me if I can test something specific which could help narrow it down :)

**Comment by omegat** [comment]
@teckel12 Update: With the OTX2.3 nightly 75 the wheel works :) 👍 👍 
More Testing tomorrow.

**Comment by teckel12** [comment]
@omegat Perfect! I couldn't 100% test it because the companion doesn't emulate the x9d+ 2019 correctly (uses the x9d+ controls). But, I reviewed the latest 2.3 OpenTX source code, so I was fairly certain it would work. It makes sense that a firmware update would fix things.

**Comment by omegat** [comment]
@teckel12 So I did some flying today and the script worked beautifully. I had to rediscover sensors once (GPS-coords read all 0s at first). After that a reboot of the TX was required due to some funky script error, but after that everything worked just great!
Keep up the great work!! 🥇

**Comment by teckel12** [comment]
@omegat At least in the OpenTX companion simulator, it seems that v2.3 requires all the sensors to be rediscovered.  Not sure if this is a bug or if this due to changes and it will be required for everyone.

Also, whenever you rediscover sensors you'll need to restart your transmitter.  Lua Telemetry looks for sensors only at startup.  If sensors change, it will look for something that doesn't exist and will likely crash.  So, restarting the transmitter is normal after rediscovering sensors.

**Comment by Target0815** [comment]
With development build on OTX 2.3.0 RC3 
X9D+ SE 2019 with Crossfire TX, FC with ArduPlane (CF returns s.port data)

RXBat = 0.0v (left column, flashing)
HDOP = 0 (right column)
Sats = 0 (right column, flashing)
GPS position flashing
"NOT OK" flashing

**Comment by teckel12** [comment]
@Target0815 I don't think OTX 2.3 is released yet? Probably delete and rediscover sensors and try again. I've heard that if upgrading from 2.2 to 2.3 you need to rediscover sensors. This is an OTX 2.3 issue that should be opened as an issue with them if this fixes it.

**Comment by Target0815** [comment]
Of course I deleted the sensors and read them in again. That's not the reason. OTX 2.3.0 is not released yet, but with RC3 not far away. The flashing comes from your script; the sensors/values are present, that's not the reason.

**Comment by teckel12** [comment]
@Target0815 LuaTelemetry just reads the sensor values. If the values are flashing, it means it's not getting the telemetry sensor values. Which is why I suggest putting in an issue on OpenTX that sensor values are not available to lua scripts.

**Comment by teckel12** [comment]
@Target0815 Also, what version of INAV are you using? Maybe a new issue would be better to open and track instead of in this issue as this about the 2019 model of the x9d, not OpenTX 2.3 issues.

**Comment by teckel12** [comment]
@Target0815 See #347 as this issue is not about OpenTX 2.3, only the 2019 model of the X9D.

**Comment by zefasm** [comment]
Hi, First thanks for your great job, it worked fine on my previous QX7. Now I have a X9D+ 2019 and I can not install your lua. I ve paste your 2 folders on "TELEMETRY" folder and it doesn't work.
![20191105_204122](https://user-images.githubusercontent.com/57415281/68241842-b5a1a300-000f-11ea-8a56-340d7b9282c7.jpg)

**Comment by teckel12** [comment]
@zefasm Are you using the development build of LuaTelemetry? Also, what version of OpenTX are you using?

**Comment by teckel12** [comment]
@zefasm Also, you don't paste anything in the telemetry folder directory. You paste it to the root folder. Please review the install instructions.

**Comment by zefasm** [comment]
Thanks a lot for your reply, I m using the last release and opentx  2.3.
I will paste on the root folder directly, thanks again

**Comment by zefasm** [comment]
Hello,  
The roll menu didn't work on my XD9+ 2019, I decided to uninstall and re install the 2 folders on root sd card.
This message appears, please could you tell me if I ve done something wrong.
Thanks
![20191210_204154](https://user-images.githubusercontent.com/57415281/70563876-5ba47800-1b8f-11ea-957d-2f5a31bcd9ce.jpg)

**Comment by simtcrom** [comment]
> Hello,
> The roll menu didn't work on my XD9+ 2019, I decided to uninstall and re install the 2 folders on root sd card.
> This message appears, please could you tell me if I ve done something wrong.
> Thanks
> ![20191210_204154](https://user-images.githubusercontent.com/57415281/70563876-5ba47800-1b8f-11ea-957d-2f5a31bcd9ce.jpg)

When I had this issue on x9 lite.
I went to SD card, completely removed inav telemetry related folders. BF Luna script related folders.
And re copied inav telemetry related stuff only.
That fixed my issue.

**Comment by zefasm** [comment]
> > Hello,
> > The roll menu didn't work on my XD9+ 2019, I decided to uninstall and re install the 2 folders on root sd card.
> > This message appears, please could you tell me if I ve done something wrong.
> > Thanks
> > ![20191210_204154](https://user-images.githubusercontent.com/57415281/70563876-5ba47800-1b8f-11ea-957d-2f5a31bcd9ce.jpg)
> 
> When I had this issue on x9 lite.
> I went to SD card, completely removed inav telemetry related folders. BF Luna script related folders.
> And re copied inav telemetry related stuff only.
> That fixed my issue.

Thanks it's work.

**Comment by craigywsm** [comment]
It works just fine, all that is needed is for the scroll wheel to work

**Comment by teckel12** [comment]
The scroll wheel isn't working as OpenTX changed the way input events work.  This makes Lua scripts written for OpenTX pre v2.3 incompatible with post v2.3.  This is a known issue, please see #349

**Comment by Mutoryu** [comment]
Having problem with saving settings on taranis 2019 (with scroll button) -2.3.4 opentx.
Cant see save option. When pressing exit then its just returning to main screen. Long press on scroll button gives 2 options - reset flight or reset telemetry (or something like that)..
After restarting TX all settings are set to default.
Im using the Development-Build, except the settings all works fine.
From scripts its seems that it loads parameters from cfg/modelname? Can someone send me his config file? i will edit it for me.. 

Also, is there any IDE for all this? im .net dev, can try to fix this

Thanks!

**Comment by Mutoryu** [comment]
If someone having same problem as me, then just change this code in iNav.lua file in Development-Build version from here - 
https://github.com/iNavFlight/LuaTelemetry/wiki/Upgrade-to-Development-Build

From:
if data.configSelect == 0 and (event == EVT_EXIT_BREAK or (event == EVT_ENTER_BREAK and data.configStatus == 34 and config[34].x > -1 and not data.armed)) then
To:
if data.configSelect == 0 and (event == EVT_PAGE_LONG or (event == EVT_ENTER_BREAK and data.configStatus == 34 and config[34].x > -1 and not data.armed)) then

seems like event == EVT_EXIT_BREAK just returning you to main taranis screen without saving..
hope this will be fixed soon :)

after this change you can save setting with long PAGE button press..

**Comment by gereic** [comment]
Hi,
I have a Taranis X9D+2019 and on the menu the scroll-wheel is not working.
Tryed already development-version but still not working.
Any suggestions ?

**Comment by craigywsm** [comment]
Is there any news on development getting the 2019 scroll wheel working?

**Comment by julianschweizer** [comment]
Is there any news on development getting the 2019 scroll wheel working?

**Comment by julianschweizer** [comment]
X9D+ 2019 working

**Comment by craigywsm** [comment]
> Is there any news on development getting the 2019 scroll wheel working?

Thanks to all involved, I can confirm the x9d SE 2019 with the scroll wheel is now navigating through the menu

**Comment by teckel12** [comment]
You're welcome!

**Comment by teckel12** [comment]
@craigywsm @julianschweizer You're welcome!

**Comment by zefasm** [comment]
Thanks for your job ! It works great with scroll on my Taranis X9D+ 2019 !!!
