### ISSUE TITLE
Incorrect display of the number of satellites.

### ISSUE THREAD

**Issue by Anak-Krakatau** [teckel12/LuaTelemetry#359]
### Describe your question
The wrong number of satellites in the script is displayed.
Transmitter: Taranis QX 7
OpenTX: 2.3.2
iNAV script 1.7.2

### Play
The number of satellites, the number of satellites from 100 to 300 each time.
But in the OSD of my FPV helmet, the correct amount is shown. (5-17) satellites.

### Expected Behavior
In telemetry, the transmitter must also have the correct number of satellites.

### Screenshots
I can add later.

### Additional context
Who faced such a problem?

**Comment by teckel12** [comment]
@Anak-Krakatau You'll probably need to upgrade INAV. You're running a very old version.
