### ISSUE TITLE
alternating views on jumper t12 its possible?

### ISSUE THREAD

**Issue by nangel0** [teckel12/LuaTelemetry#360]
is alternating views on jumper t12 its possible? pressing the left and right buttons on default view does nothing on jumper t12

### To reproduce
latest opentx on jumper t12
r9m telemetry enabled
default view on inav lua script works , others doesnt

**Comment by teckel12** [comment]
@nangel0 you can change views from the config menu. You probably can't change views while in a view due to non-standardization of controls from transmitter to transmitter. This will be resolved when OpenTX merges support for Jumper/Nirvana transmitters in the main source code.

**Comment by PasiRuo** [comment]
Latest LuaTelemetry worked for one period of OTX2.3.0nightlies.

Virtualbuttons have since changed. I can change view with shortENT, but not possible to enter config-menu. I found nothing to still be OTXmerged regarding improvement of buttons for T12

**Comment by PasiRuo** [comment]
to put in other words, T12 passes virtual button test ok
https://github.com/opentx/opentx/blob/2.3/radio/util/lua/lua_event_test.lua
but LuaTelemetry does not open config with virtual_menu
