### ISSUE TITLE
Different screen on my horus x10 

### ISSUE THREAD

**Issue by fmartinezo** [teckel12/LuaTelemetry#362]
Hello i have different screen on my horus that the screen wich appears on github see my photo specially on top left panel and compare whith your github panel.
What is wrong on my radio?
![horus imagen](https://user-images.githubusercontent.com/38476783/70853265-e5b05180-1eab-11ea-893e-e632706cf02c.jpg)
![iNavHorus](https://user-images.githubusercontent.com/38476783/70853270-ed6ff600-1eab-11ea-83eb-6ad9638dd979.png)

**Comment by teckel12** [comment]
Are you flying FlySky or Crossfire?  If you're flying FlySky, is seems you don't have `frsky_pitch_roll` set to `ON` as required.  Please see the installation instructions:

https://github.com/iNavFlight/LuaTelemetry/wiki/Installation#inav-configurator-telemetry-setup

**Comment by fmartinezo** [comment]
I am using frsky x8r and rsxr. The problem was i do not read the 3rd point
of change cli parameter pitch-roll. As Soon is i Will arrive at home i try
It
Thanks

**Comment by fmartinezo** [comment]
Ready, The problem was that set frsky_pitch_roll = ON and rediscover new sensors was new for me. All is working fine. Thanks
