### ISSUE TITLE
[RESOLVED] INAV Telemetry - Battery critical warning and Fuel % showing.

### ISSUE THREAD

**Issue by simtcrom** [teckel12/LuaTelemetry#363]
### Describe your question
Even though I have full battery, Taranis telling battery critical and battery 0 %
Any one help me fix it please?

**Comment by simtcrom** [comment]
This issue is resolved, I had mistakenly rename telemetry sensor for Fuel to Mah.
Deleted all sensors and rediscovered again, all issues resolved.

**Comment by simtcrom** [comment]
This issue is resolved, I had mistakenly rename telemetry sensor for Fuel to Mah.
Deleted all sensors and rediscovered again, all issues resolved.

**Comment by darvin** [comment]
I have the same issue, removing sensors and rediscovering of them doesn't help

**Comment by iabdullah98** [comment]
i have the same problem and it didnt solve it
