### ISSUE TITLE
Crossfire, Jumper T16, No pitch, roll yaw

### ISSUE THREAD

**Issue by gdgabq** [teckel12/LuaTelemetry#367]
### Describe your question
Using new Jumper T16, OpenTX 2.3.4, Crossfire micro receiver, Inav with Omnibus F4, V5.
Setup using MAVLINK protocol on soft serial port. 

GPS, Alt,RSSI, Speed, heading active but no pitch, roll, yaw. I have confirmed sensors respond in the telemetry page of the model when discovering new sensors.

Any suggestions would be appreciated. Thanks

**Comment by teckel12** [comment]
@gdgabq How do you have `frsky_pitch_roll` set in INAV?  This is required to be set to `ON` as per the install instructions: https://github.com/iNavFlight/LuaTelemetry/wiki/Installation#inav-configurator-telemetry-setup
