### ISSUE TITLE
Display and voice alerts for launch mode (NAV LAUNCH)

### ISSUE THREAD

**Issue by avsaase** [teckel12/LuaTelemetry#369]
I am setting up launch mode (`NAV LAUNCH`) and I noticed LuaTelemetry does not support display and voice alerts for this mode and instead displays `angle mode` (which I assume is active behind launch mode. I'm using the permanently enable launch mode setting, but it is possible I'll forget this in the future so it would be nice to have the Tx callout that launch mode is active. 

I'm using the development branch on a 2019 X9D+ (non-SE) per the advice in issue #344 .

**Comment by teckel12** [comment]
@Alexbombali `NAV LAUNCH` is not a flight mode which is included in telemetry, so LuaTelemetry can't show it.  From conversations with other INAV developers, it was deemed not a required flight mode to communicate.  There's limited flight modes which can be transmitted with the sensor, and it's already maxed out so it can't be added to INAV.
