### ISSUE TITLE
Telemetry working, shows 0v at all times

### ISSUE THREAD

**Issue by darvin** [teckel12/LuaTelemetry#375]
Horus x12s, matek 405 wing FC, tbs crossfire telemetry.

Telemetry is working, shows correct voltage in the telemetry screen of the model, shows 0 v in Battery and 45mAh on the widget.

What should I try?

**Comment by teckel12** [comment]
@darvin Sounds like something isn't setup right. Go through the installation instructions from the top and if you're still having issues please list the versions of INAV, OpenTX and other details as it's something unique to your setup.
