### ISSUE TITLE
Taranis X9D 2019 SE - Can't use Scroll Wheel to navigate Menu

### ISSUE THREAD

**Issue by tobiasbischoff** [teckel12/LuaTelemetry#376]
### Describe the bug
I can invoke the Menu using the Menu Key but i can't do any configuration because Scroll Wheel movement is not detected.

### To reproduce
Invoke Script, press menu, try to scroll

### Expected behavior
As per Manual i should be able to scroll thru the options and make changes.

### Radio and model settings
X9D SE 2019 on OpenTX 2.3.7

**Comment by tobiasbischoff** [comment]
Sorry, I did not now that I have to use development release for this to work. Now its flawless.

**Comment by Kacmarik** [comment]
My LUA scripts do the same thing.  What version of what did you use to resolve this issue?  This problem is killing me.
