### ISSUE TITLE
AHI jumping around

### ISSUE THREAD

**Issue by wx4cb** [teckel12/LuaTelemetry#378]
### Describe the bug
Transmitter T16 (also happens with X9D+), when i go into the LUA script the AHI in the top left is always jumping around, even when the aircraft is standing still. not sure if it's a setting i need to change or not.

CLI Dump (diff) 

[INAV_cli_WX4CB-Harrier_20200417_155042.txt](https://github.com/iNavFlight/LuaTelemetry/files/4494954/INAV_cli_WX4CB-Harrier_20200417_155042.txt)

See attached video: https://youtu.be/gjXLpJQOQDM

Model name is "Harrier"

[Harrier.zip](https://github.com/iNavFlight/LuaTelemetry/files/4494946/Harrier.zip)

**Comment by wx4cb** [comment]
bump

**Comment by teckel12** [comment]
@wx4cb View the telemetry values and see what the `AccX`, `AccY`, `AccZ` values are doing.

**Comment by wx4cb** [comment]
will do when i go out tomorrow.. welcome back btw 👯

**Comment by wx4cb** [comment]
@teckel12 

ok, just remembered about this..... i found out the problem.... it's because i have the sensor values aset as degrees (cus i know degrees not radians :D) 

must be a conversion thing you're doing in the script
