### ISSUE TITLE
Cannot get into Configuratuion menu

### ISSUE THREAD

**Issue by markandkymward** [teckel12/LuaTelemetry#385]

**Comment by kasatka60** [comment]
Jumper t12 pro opentx 2.3.8 Nightly builds
LuaTelemetry 1.7.2
Cannot get into Configuratuion menu

**Comment by kasatka60** [comment]
but is there another script that works normally with telemetry inav?

**Comment by wx4cb** [comment]
throttle stick up and to the right should work

**Comment by teckel12** [comment]
Duplicate of #349
