### ISSUE TITLE
Modifying configuration on Jumper t12 pro

### ISSUE THREAD

**Issue by kieranhood** [teckel12/LuaTelemetry#388]
### Describe your question
I'm running this on a Jumper T12 pro running opentx-t12 2.3.7 and am trying to modify some of the configuration settings. I cannot access the configuration menu but was wondering if it is possible to change the options within a file? I specifically want to change the levels at which the battery alarms kick in.

**Comment by kasatka60** [comment]
Looks like this script is no longer being developed

**Comment by kieranhood** [comment]
Yeah its looking like that. Do you know if there are any alternative projects that take INAV telemetry onto a Jumper T12?

**Comment by teckel12** [comment]
Duplicate of #349
