### ISSUE TITLE
script syntax error bad argument #1 to 'min"

### ISSUE THREAD

**Issue by JupaCreations** [teckel12/LuaTelemetry#389]
### Describe your question
<X7 with Inav lua telemetry script added results in above error after a while.
After the first time installing the script it worked fine and I could use it.
Suddenly out of the blue after a few flying days when you enter the LUA script screen I get this message.
New model made with same result.
Took a new SD and copied saved old model settings without LUA script added to the SD.
Old settings working fine for models.
Added the LUA script again on the card and set up one model with the script for test.
It works fine.
Suddenly out of the blue it stops working again with same error after a few days flying..
No models added or whatever which can cause memory shortage.
Philips 8GB class 4 SD card.
![20200611_195905](https://user-images.githubusercontent.com/17322922/84424074-d5411f80-ac1f-11ea-95ae-0b5273b1a32d.jpg)
![20200611_195838](https://user-images.githubusercontent.com/17322922/84424076-d5d9b600-ac1f-11ea-8265-1b2f22229efc.jpg)

### To reproduce
1. Press PAGE button

### Expected behavior
<Show telemetry screen>

### Screenshots
<attached>

Strange problem which not seem a bug as I cant find the error message with google.

Paco

**Comment by zsdanlli** [comment]
I got the same problem yesterday, fixed by deleting the modelname.dat file in /scripts/telemetry/inav/cfg.

**Comment by JupaCreations** [comment]
HI, I performed your steps on the TX and confirm the script is working again.
Still unknown why it happens.

Thanks for the assistance and solution.

Paco Raap

**Comment by teckel12** [comment]
Sounds like the configuration `model.dat` got corrupted.  I've never experienced this, but it can happen (SD cards are prone to corruption as well).  I would love to see the file.  If it happens again, please get me a copy of the dat file.

**Comment by JupaCreations** [comment]
Hi, next time I will save the data from the SD card for examination and debugging.
But the removal of the model.dat is an easy but dirty solution for now.

BTW thanks again for a beautyfull script.

Paco Raap

**Comment by JupaCreations** [comment]
Problem happened again. When switching from ARwing900 to CS Wing1000.
All model.dat files that were in the folder are zipped.
[lua script.zip](https://github.com/iNavFlight/LuaTelemetry/files/4943966/lua.script.zip)
Let me know if you can find something.

Thanks, Paco

**Comment by patemil** [comment]
Got the same issue today, compared with another setup and my .dat file had a -1 value in last position that in the other configuration was 0. Changed it to 0 and it started to work again. 
Seems like the script can't handle negative values on one of the parameters.

@JupaCreations I see the same issue in your CSwing1000.dat

**Comment by JupaCreations** [comment]
I currently run a Radiomaster TX16S with the script too. Sofar did not had this problem.

**Comment by Stringbrakr** [comment]
had the same problem today .

**Comment by teckel12** [comment]
There's a PR for this #424

**Comment by Asafsol** [comment]
Im having the same issue with gx12
cant find dat file to delete
any solution?
