### ISSUE TITLE
Unable to playAudio() after update to OpenTX 2.3.8  with "Path too long" error message

### ISSUE THREAD

**Issue by paulo-sousa** [teckel12/LuaTelemetry#390]
### Describe the bug
I just upgraded from OpenTX 2.3.7 to 2.3.8, copying the LuaTelementry-en files and configuration when upgrading the SD Card contents. I am using a Taranis Q X7 radio, with language in English.

### To reproduce
1. Upgrade a Taranis Q X7 to OpenTX 2.3.8.
2. Copy the iNav Telemetry Script 1.7.2 (LuaTelementry-en.zip) over to SD Card.
3. Configure a model with FrSky Telemetry.
4. Activate iNav Telemetry Script.
5. Turn model on, so that telemetry is received.
6. Perform a function that would trigger a voice alert (e.g. "Arm Motors").
7. **"Path too long"** error message is displayed on screen.

### Expected behavior
The sound alert should be heard and no error message should be shown.

### Screenshots
![20200614_151301](https://user-images.githubusercontent.com/25321797/84597383-91d2f500-ae5b-11ea-8776-51960792bbf4.jpg)

### Radio and model settings
[RadioAndTelemetrySettings.zip](https://github.com/iNavFlight/LuaTelemetry/files/4776728/RadioAndTelemetrySettings.zip)

### Additional context
OpenTX 2.3.8 was released yesterday. I reverted back to OpenTX 2.3.7 and the problem was gone (sound played correctly).

**Comment by paulo-sousa** [comment]
Retested with OpenTX 2.3.9, which was released a few minutes ago and issue keeps occurring.
Also happens when selection other non-english voice languages.

**Comment by paulo-sousa** [comment]
Retested with OpenTX 2.3.9, which was released a few minutes ago and issue keeps occurring.
Also happens when selecting other non-english voice languages.

**Comment by paulo-sousa** [comment]
I printed out the call to playFile() and it seems correct, so the issue seems to be with OpenTX not accepting the around 33~38 characters.

In this example, it fails with this file:
**/SCRIPTS/TELEMETRY/iNav/en/good.wav**

![20200614_223918](https://user-images.githubusercontent.com/25321797/84604862-f2c8f000-ae90-11ea-9bd5-f005ec21c48d.jpg)

**Comment by paulo-sousa** [comment]
This seems to be an issue with OpenTX 2.3.8 & 2.3.9.

I opened an issue in the OpenTX project:
["Path too long" error when calling playFile() with 37+ characters ](https://github.com/opentx/opentx/issues/7739)

**Comment by Stormdad** [comment]
I am also having the same issue after upgrading to OTX 2.3.9.

**Comment by afterhender** [comment]
Hi, I have the exact same problem.
I'm using a Taranis Qx7s. Any solution found ?

**Comment by paulo-sousa** [comment]
I submitted a bug directly to OpenTx with detailed information. This was immediately fixed and scheduled for [OpenTX 2.3.10](https://github.com/opentx/opentx/milestone/58?closed=1), but this milestone of OpenTX hasn't been released yet.

As soon **2.3.10** is released, you can update the firmware and the issue should be automatically fixed.

**Comment by afterhender** [comment]
Great news, thank you

**Comment by Stormdad** [comment]
> I submitted a bug directly to OpenTx with detailed information. This was immediately fixed and scheduled for [OpenTX 2.3.10](https://github.com/opentx/opentx/milestone/58?closed=1), but this milestone of OpenTX hasn't been released yet.
> 
> As soon **2.3.10** is released, you can update the firmware and the issue should be automatically fixed.

Thank you for getting this issue addressed ! I use this script A LOT and look forward to it working again.

**Comment by teckel12** [comment]
Nice job everyone identifying this and getting it fixed in OpenTX!  Due to this and a few other issues in the 2.3.x cycle, I'm going to require all future versions of LuaTelemetry run on OTX 2.3.10+
