### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by chconst00** [teckel12/LuaTelemetry#391]
Hello and thank you for this great script, great work!! Im trying to make a small modification for my needs but i’m not able to rebuild from source since it doesn’t work on my taranis x9d+ when i do so. In companion it works fine. Even if i rebuild the source code as is, my taranis complains about the memory error (call of a nil function), especially when switching to pilot view. It looks like you are using a specific lua code minifier and with a specific version of luac for your releases.. can you please share that as well?

**Comment by teckel12** [comment]
You must pre-compile everything using the OpenTX Configurator.  I use a specific development environment and a script that sets up symbolic and hard links which would only work on Windows and only if certain software is installed.

Basically, it would be a bit of a challenge (and fairly restrictive) to setup a build environment.  I've considered detailing it, but it's a bit of a pain.  Are you running Windows?
