### ISSUE TITLE
Some flight modes not displayed or called out when using Crossfire

### ISSUE THREAD

**Issue by kornface13** [teckel12/LuaTelemetry#392]
### Describe the bug
Voice prompts don't call out certain modes when using Crossfire.  Specifically ACRO, Altitude Hold, Cruise.  I think RTH as well.  These do work when using R9.  Not sure if this impacts all controllers, but it does impact my Taranis X9D+.  The only flight mode that do appear to work are Manual and Angle.  I haven't tested all modes.

### To reproduce
1.) Setup telemetry with Crossfire, and INAV LUA
2.) Enable Manual, Angle, and Air/Acro modes.
3.) Switch between the modes.  There will not be a callout for acro.  The screen will continue to display the previos mode insead of displaying Acro.  

### Expected behavior
Screen should display ACRO and the acro wav file should be played.  

### Screenshots
https://youtu.be/bgeVNU6ilTI?t=16

### Radio and model settings
OpenTx 2.2.4
Planes on Inav 2.2.1 and Inav 2.4.1 both exhibit the same behavior.

**Comment by teckel12** [comment]
Not all flight modes are reported by Crossfire, so they can't be reported.
