### ISSUE TITLE
Can this lua working on radiomaster tx16s?

### ISSUE THREAD

**Issue by vanawaker** [teckel12/LuaTelemetry#394]
Hi~

Can I install this lua to radiomaster tx16s, I thought it may like jumper t16, can it work?

Zax

**Comment by Argon1978** [comment]
Hi vanawaker,
Yes you can install this on a Radiomaster TX16S.
It runs OpenTX so it will work.
I also installed it on my TX16s and it works very nice

**Comment by vanawaker** [comment]
Thanks~ It works very well on my radio XD
