### ISSUE TITLE
INAV lua script with crossfire

### ISSUE THREAD

**Issue by mstranger1** [teckel12/LuaTelemetry#398]
### Describe the bug
Hi all .Am tryn to make work inav lua telemetry on radiomaster t16s - crossfire micro tx - crossfire nano rx. Lua is working beafore plug drone , but if i try run script after plug battery i get "background()bad argument #1 to getValue(string expected , got nil)"Any ideas?

**Comment by wx4cb** [comment]
Reload the script. Works fine with mine

**Comment by paultsanghy** [comment]
I've got the same syntax error message on my zorro. Any fixes for this potential bug?
