### ISSUE TITLE
When selecting model the model name is not present when INAV Tel. is installed on Jumper T16.

### ISSUE THREAD

**Issue by Gaylian** [teckel12/LuaTelemetry#404]
When selecting model in OpenTX 2.3.9 the model name is not present when INAV Tel. is installed on Jumper T16 but when INAV Tel, scripts are deleted the name returns. OpenTX tells me it is INAV Tel script that is the problem. How do I fix this problem ?

**Comment by Gaylian** [comment]
Why no answer to issue ?

**Comment by teckel12** [comment]
@Gaylian See: https://github.com/iNavFlight/LuaTelemetry/issues/416#issuecomment-780085586
