### ISSUE TITLE
Activating iNav widget changes text color on other widgets

### ISSUE THREAD

**Issue by RC-SOAR** [teckel12/LuaTelemetry#409]
### Describe the bug
Activating iNav widget changes text color on other widgets. 
Radio: Jumper T16, Horus X12S
iNav 1.7.2
OpenTX 2.3.9

### To reproduce
1. Install iNav on SD card
2. Go to Telemetry menu
2. Select default OpenTX theme, set background to white, main color to any dark color
3. Configure page 1 for iNav widget
4. Configure page 2 for Channels widget
5. Press {Rtn} to exit
6. Power cycle radio. On restart, displays Channels widget
7. Press {Page up} to iNav 
8. Press {Page up} to Channels widget

### Expected behavior
Channels widget color was black, and should remain black. But it changes to white after iNav activated.
Similar happens with ShowItAll widget (as supplied with  TX16S)

### Screenshots
Screenshot 1: set theme colours (default theme)
Screenshot 2: Channels widget before
Screenshot 3: iNav
Screenshot 4: Channels widget after

![Bug00001](https://user-images.githubusercontent.com/6317479/90833708-82cb6000-e340-11ea-8d9d-759f27de105b.png)
![Bug00002](https://user-images.githubusercontent.com/6317479/90833717-852dba00-e340-11ea-8c53-884472ff9af5.png)
![Bug00003](https://user-images.githubusercontent.com/6317479/90833719-87901400-e340-11ea-8eed-3c26c49c1b56.png)
![Bug00004](https://user-images.githubusercontent.com/6317479/90833721-88c14100-e340-11ea-9484-4ef997bcbc1b.png)

**Comment by PD5DJ** [comment]
Can confirm this

**Comment by xxJohnxx** [comment]
Can confirm, this happens on the RadioMaster TX16S as well.

**Comment by porlock** [comment]
i have it to on RadioMaster TX16S

**Comment by expipiplus1** [comment]
Should this be considered an opentx bug, improper sandboxing of widgets.

**Comment by wizardrnd** [comment]
Try to enable the "restore" parameter on the widget settings. See #426 for details.
