### ISSUE TITLE
Menu still accessible true stick access, TX16S

### ISSUE THREAD

**Issue by DJJeffP** [teckel12/LuaTelemetry#412]
When the script is started, you can access it true put the left stick in the upper right corner (ALI 100% + YAW 100% Right). 
But the function to go into the menu true the "SYS button" also works. 
When flying I get sometimes in the menu screen because my stick hits the upper right corner. 

It would be nice to have a option to turn this future off in the menu and it will only be accessible true the "SYS button" end exit it with the "RTN Button" on the Radiomaster TX16S or maybe also other OpenTX Transmitters.

**Comment by Xedos9er** [comment]
See here:
https://github.com/iNavFlight/LuaTelemetry/issues/396

You can access the menu, since arm status is not recognized.
