### ISSUE TITLE
Display on a standalone screen for onboard FPV

### ISSUE THREAD

**Issue by flyingbandit** [teckel12/LuaTelemetry#413]
This is a fantastic display. I would love to know if this could be displayed on a standalone screen for an onboard FPV cockpit.

Inav FC MSP out -> F4 board with libraries/widgets & spi interface (the basic hardware the transmitter would need for displaying the graphics) -> Small LCD for scale cockpit

For scale FPV with analog or for HD fpv this would be incredible to be able to display full graphical telemetry in your scale cockpit.

**Comment by npmullins** [comment]
that would be F&#KING HANDYYYY

**Comment by andrewboulton46** [comment]
This would amazing and very useful for scale pilots. A real leap forward for the hobby and scale flying.
