### ISSUE TITLE
Radiomaster TX16S Model Names disappear in model screen after Lua install

### ISSUE THREAD

**Issue by terrorswellfpv** [teckel12/LuaTelemetry#416]
Using latest version 1.72

Radiomaster Open tx version is 2.3.8

![Bug](https://user-images.githubusercontent.com/28787640/94265353-5a69ef00-ff06-11ea-8db3-9d57fea20915.jpg)

**Comment by JupaCreations** [comment]
Same problem. If it is LUA related no idea but model names sometimes disappear.

**Comment by mastersurferde** [comment]
Hi,
I have the same problem with the Jumper T16 and the actual OpenTX 2.3.10N3xx (also with previous nightly versions and official versions). The proplem is always present if you use a model with crossfire (and lua-telemetry) and you disconnect the crossfire module bevore you change the model.
Best regards,

**Comment by Gaylian** [comment]
I have same issue with Jumper T16. See issue #404. I placed an issue with OpenTx and their reply was it's a telemetry LUA problem. They have seen this issue before.!

**Comment by ojoojoo** [comment]
Same problem on a Radiomaster TX16S, model names disappear with OpenTX 2.3.10

**Comment by terrorswellfpv** [comment]
Change the color of the background to blue and model names will reappear. This is the fix until it gets patched.

**Comment by ojoojoo** [comment]
Thanks for the answer, selecting a default widget and rebooting the radio also works.

**Comment by Tygrys-1** [comment]
It is not the model names disapear, but the font color is changed to white.

**Comment by FrankPetrilli** [comment]
See #426 for a mitigation - enabling the "restore" setting under the widget settings.

**Comment by teckel12** [comment]
Correct, this is an issue with OpenTX as the color settings are global.

The solution is https://github.com/iNavFlight/LuaTelemetry/wiki/Installation#installsetup-lua-telemetry-on-transmitter under `Install/Setup Lua Telemetry on Transmitter` > `Horus/Jumper T16` > `g`:

Optionally (while still selecting the iNAV script), long-press Enter, select Widget settings where you can enable Restore (to restore your theme's colors) and set your theme's Text color and Warning color
