### ISSUE TITLE
Artificial horizon is going the wrong way when FC is rotated 180 degrees in INav 2.5.0

### ISSUE THREAD

**Issue by ojoojoo** [teckel12/LuaTelemetry#418]
### Describe the bug
Artificial horizon is going the wrong way when the FC is rotated 180 degrees in INav 2.5.0 on a Radiomaster TX16S, left is right and right is left. In Inav everything is displayed correct and the Quad is flying perfect.

### To reproduce
Open the InavFlight Widget and turn the Quad to the left, in the screen it shows to the right.

### Expected behavior
Left is left and right is right.

**Comment by teckel12** [comment]
I believe you're not understanding the artificial horizon correctly.  It's done in a first-person perspective, as if you were inside the cockpit.
