### ISSUE TITLE
Spurious battery warnings when fuel sensor is removed

### ISSUE THREAD

**Issue by skorokithakis** [teckel12/LuaTelemetry#419]
I have a RadioMaster with R9 and an F405-WING FC. I removed the fuel sensor, but whenever I arm I get "battery critical, zero percent", which shows me that Lua Telemetry is still trying to read from the fuel sensor. Adding the sensor back with the units on the FC set to `PERCENT` fixes the issue.

**Comment by skorokithakis** [comment]
No

**Comment by teckel12** [comment]
The fuel sensor is required.  It's not designed to work without a fuel sensor.

**Comment by skorokithakis** [comment]
Hmm, I was going by [your comment here](https://github.com/iNavFlight/LuaTelemetry/issues/353#issuecomment-542025852), is that not the case then?

**Comment by teckel12** [comment]
Are you rebooting your transmitter after removing the sensor?

**Comment by skorokithakis** [comment]
I did, but I'll try again and let you know.
