### ISSUE TITLE
Fuel sensor set to mAh doesn't work

### ISSUE THREAD

**Issue by skorokithakis** [teckel12/LuaTelemetry#420]
If I set `smartport_fuel_unit` to `MAH` on the FC, the fuel sensor starts at 0% and keeps climbing, which is the wrong behaviour.

**Comment by skorokithakis** [comment]
Thanks, stalebot.

**Comment by teckel12** [comment]
@skorokithakis You just need to set the Fuel Unit configuration to mAh as well

Fuel Unit - Match to INAV CLI value smartport_fuel_unit (default: Percent)

See the configuration menu here:  https://github.com/iNavFlight/LuaTelemetry/wiki/Configuration-Settings

**Comment by skorokithakis** [comment]
It's been a while, but I'm fairly certain it was changed to match on both sides and I still got the behavior.
