### ISSUE TITLE
Changing BATT Percentage and MIN/Max if Roll is applied?

### ISSUE THREAD

**Issue by fellpower** [teckel12/LuaTelemetry#421]
If im using lua telemetry on my TX16S my Capacity monitor is chaning between capacity and a min max value. if it does that, my LQ (Crossfire) is stuck at the lowest postion. 

that might be a feature, but as i look at my LQ, all is fine, because i changed it with my roll stick. thats so annoying.

how do i disable this "feature"? (maybe in the code?)

**Comment by cqmiao** [comment]
me too,my t16 pro is opentx 2.3.10,with CRFS TX V2，Changing BATT Percentage and MIN/Max if Pitch is applied,LQ is change too

**Comment by teckel12** [comment]
That's a feature.  It allows you to see the min/max or last values.  It only does that when not flying.
