### ISSUE TITLE
GPS Good Message occurs also when GPS is not Fix

### ISSUE THREAD

**Issue by SteffenFPV** [teckel12/LuaTelemetry#430]
If GPS is starting up the last (ore random if backup battery is empty) latitude and longitude data are provided ( ~=0) also when no ore less sattelites are tracked,  and the fix is not valid.

In Inav.lua line 181:

if data.satellites > 1000 and gpsTemp.lat ~= 0 and gpsTemp.lon ~= 0 then

So I suggest to require additional at least 5 Sattelites (according to INAV firmmware) for a valid fix:

if data.satellites % 100 >= 5 and gpsTemp.lat ~= 0 and gpsTemp.lon ~= 0 then

**Comment by teckel12** [comment]
data.satellites > 1000 means INAV has reported a GPS lock.  You can set the number of satellites required for a GPS lock in INAV.
