### ISSUE TITLE
inav(lua telemetry ) + PixHawk cube orange

### ISSUE THREAD

**Issue by darthh163** [teckel12/LuaTelemetry#432]
Good evening, I have PixHawk Cube orange. Is it possible to install Inav on this platform to transmit telemetry to the FlySky nirvana console in conjunction with Lua Telemetry. Is there any development for this inav flight controller? Are there any workarounds for receiving data for Lua telemetry on Nirvana?

**Comment by digitalentity** [comment]
Unfortunately Cube FCs are not supported at the moment. Cube Orange is based on H7 processor, which is not supported by INAV yet, but we're working on it.

**Comment by darthh163** [comment]
It's a pity ((and when is the beta release expected? Ready to test))

**Comment by teckel12** [comment]
Unrelated to LuaTelemetry.
