### ISSUE TITLE
Why does LuaTelemetry widget not work on OpenTX firmware simulator? 

### ISSUE THREAD

**Issue by wizardrnd** [teckel12/LuaTelemetry#439]
I tried running it by simulate opentx-tx16s, opentx-t16, opentx-x10 and opentx-x12s with OpenTX 2.3.10 and 2.3.11, but it doesn't show up on selecting page widget

**Comment by teckel12** [comment]
If LuaTelemetry isn't listed as a Widget, it was installed in the incorrect location. Please see the following instructions on the exact steps to install to your transmitter's folder:

https://luatelemetry.readthedocs.io/en/latest/Getting-Started/#installsetup-lua-telemetry-on-transmitter

**Comment by wizardrnd** [comment]
LuaTelemetry is listing and working correct on my "real" Radiomaster TX16S, but it not listing and not working on OpenTX firmware simulator. Another LUA scripts and widgets (for example, FrskyTelemetryScript and HorusMappingWidget by yappu) are listing and working on simulator too. But iNAV LuaTelemetry is working on real device only.

**Comment by teckel12** [comment]
https://github.com/teckel12/LuaTelemetry/issues/22#issuecomment-781359515

**Comment by nm17** [comment]
Can confirm that I have the same issue on the simulator

**Comment by teckel12** [comment]
I do not experience this, it's my primary development environment.  Keep in mind, LuaTelemetry is currently designed for OpenTX 2.2 due to breaking changes in OpenTX 2.3.
