### ISSUE TITLE
Can't enter the menu on Jumper T12

### ISSUE THREAD

**Issue by kasatka60** [teckel12/LuaTelemetry#440]
Jumper T12 pro openTX 2.3.11
LuaTelemetry v1.7.3
How to enter the menu?

**Comment by nm17** [comment]
@kasatka60 have you tried going into the menu like it is described in the docs?

https://luatelemetry.readthedocs.io/en/latest/Configuration-Settings/#horusjumper-t16

**Comment by teckel12** [comment]
@kasatka60 Not sure about this fork, but my v1.7.4 build was supposed to resolve this, you can [get it here](https://github.com/teckel12/LuaTelemetry).

**Comment by kasatka60** [comment]
Haven't tried it yet. Have you implemented menu entry as a jumper-t16? 
I will try.

**Comment by nm17** [comment]
> Haven't tried it yet. Have you implemented menu entry as a jumper-t16?
> I will try.

It should theoretically work on any transmitter I think, so give it a try.

**Comment by PasiRuo** [comment]
works ok here with  [https://github.com/iNavFlight/LuaTelemetry/pull/400](url)

**Comment by kcneato** [comment]
I have similar issue on Jumper t lite. Cant access the menu button with sys neither the stick comands.

**Comment by kasatka60** [comment]
> It should theoretically work on any transmitter I think, so give it a try.

Don't work

**Comment by kasatka60** [comment]
> I have similar issue on Jumper t lite. Cant access the menu button with sys neither the stick comands.

Try this:
https://yadi.sk/d/yMzA1EA6blM2EQ

**Comment by kcneato** [comment]
> > It should theoretically work on any transmitter I think, so give it a try.
> 
> Don't work

i tried the stick commands with the tarranis to get the menu up but did not work (the button works great). Maybe something  wrong with t lite opentx image still, waiting for the official updated for the jumper

**Comment by nm17** [comment]
We are working on some new important stuff for the repo, so expect some delays with this. I'll make sure this gets done ASAP.
