### ISSUE TITLE
CRSF Arm status not working

### ISSUE THREAD

**Issue by Xedos9er** [teckel12/LuaTelemetry#441]
First of all, great to see you back here @teckel12 !
Can you please add the mentioned fix to the code.

See:https://github.com/iNavFlight/LuaTelemetry/issues/396#issuecomment-782928916

_Originally posted by @Xedos9er in https://github.com/iNavFlight/LuaTelemetry/issues/396#issuecomment-782928916_

**Comment by teckel12** [comment]
@Xedos9er This change is now merged to master and included in the [v1.7.5 release](https://github.com/teckel12/LuaTelemetry/releases/tag/v1.7.5).
