### ISSUE TITLE
Add config options for controlling warning beeps and vibration feedback

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#60]
* [x] All Vibration - on/off
* [x] All Beeper - on/off
* [x] Battery Beep/Vibrate - on/off
* [x] RSSI Beep/Vibrate- on/off
* [x] RTH Beep/Vibrate- on/off
* [x] Headfree Beep/Vibrate- on/off

Any other options users would like?

**Comment by Allerhopp** [comment]
I would prefer a solution analog OpenTX RSSI warnings:
As default one beep and one vibration, if the status worsens. This is useful for Battery and Failsafe only imo. RSSI is already covered by OpenTX.
Additional alarms can then be made configurable.
My own experience, when failsafe happened with the recent version: two problems occured simultaneously: control link broken, OK, but why is my TX continously beeping and shaking? ;)

**Comment by teckel12** [comment]
4 of 6 added in #62

**Comment by teckel12** [comment]
@Allerhopp LuaTelemetry's feedback is designed to enhance what the transmitter does by default. A warning would be just a single feedback. Critical information provides feedback every 5? seconds.

For example, if RSSI is below the critical level that you've set in your transmitter LuaTelemetry will keep warning you of this every 5? seconds. Same is true with critical battery level. Similar as well is max altitude (except every 10? seconds because it also speaks the altitude).

In all cases, when there's something critical, there will be flashing inverted text to go along with it. So, when RTH was flashing, that would be the indication as to why it's beeping/vibrating.

Pull request #62 (untested) adds new config features to better control this. It currently addresses turning RTH and HF from critical to just information. Also, you can totally turn off beeping and vibration feedback independently.  I still need to think about battery and RSSI warnings as how those should be controlled.

**Comment by teckel12** [comment]
RSSI, battery and altitude feedback/warning options added to config menu in #62

**Comment by teckel12** [comment]
Included in v1.2.1
