### ISSUE TITLE
Add support for FrSky D-series receivers

### ISSUE THREAD

**Issue by teckel12** [teckel12/LuaTelemetry#95]
See: [Modify FrSky D-series telemetry for compatibility with Lua script](https://github.com/iNavFlight/inav/pull/3116) from @alexeystn

Only README changes should be required for LuaTelemetry:
* [x] Note that D-series receivers are supported
* [x] Add list of common supported D-series receivers
* [x] Note that on D-series receivers the `07` sensor name is changed to `Dist` (like how the `0420` is changed with X-series receivers)
* [x] Maybe a code change to detect the `07` sensor automatically like how it's now done for the `0420` sensor

**Comment by SPlissken** [comment]
Happy to test, I've got the hardware ready to go.

**Comment by teckel12** [comment]
@SPlissken I can make a build for you with the changes.  What target do you need?

**Comment by teckel12** [comment]
@SPlissken The [PR for the D-series telemetry](https://github.com/iNavFlight/inav/pull/3116) hasn't been merged to development yet, so it's not part of 2.0.0.  Following is the D-series PR for SPRACINGF3:

[inav_1.9.1_SPRACINGF3.hex.zip](https://github.com/iNavFlight/LuaTelemetry/files/1991651/inav_1.9.1_SPRACINGF3.hex.zip)

**Comment by SPlissken** [comment]
@teckel12 All looks good. I don't have a current sensor on the build used for testing but the rest of the data came through fine and displayed correctly on an X7. I didn't validate any of the telemetry data displayed in the script but the voltage seemed accurate and the data looked meaningful.

**Comment by teckel12** [comment]
@SPlissken 👍

**Comment by teckel12** [comment]
Added in #108

**Comment by teckel12** [comment]
Merged into [1.3.0](https://github.com/iNavFlight/LuaTelemetry/releases/tag/1.3.0)
